# Generated by Django 5.0.7 on 2024-12-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Myusers',
        ),
    ]
